name: 24/7 AI Story Stream

on:
  schedule:
    # سيقوم بالنشر كل ساعتين بالظبط (12 حلقة في اليوم)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Fast Install FFmpeg
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install requests edge-tts asyncio groq

      - name: Run YouTube Stream
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
        run: python main.py
      - name: Run Stream
        run: |
          until python main.py; do
           echo "Stream crashed with exit code $?. Respawning.." >&2
          sleep 5
          done
